import type { DOMKeyframesDefinitionAny } from "@/types/animation";


export const effects: Record<string, DOMKeyframesDefinitionAny> = {
  fadeIn: { opacity: [0, 1] },
  fadeOut: { opacity: [1, 0] },
  slideInLeft: { x: ["-100%", "0%"], opacity: [0, 1] },
  slideInRight: { x: ["100%", "0%"], opacity: [0, 1] },
  slideInUp: { y: ["100%", "0%"], opacity: [0, 1] },
  slideInDown: { y: ["-100%", "0%"], opacity: [0, 1] },
  zoomIn: { scale: [0.85, 1], opacity: [0, 1] },
  zoomOut: { scale: [1, 0.85], opacity: [1, 0] },
  rotate: { rotate: ["0deg", "360deg"] },
  bounce: { y: ["0px", "-30px", "0px"] },
  flip: { rotateY: ["0deg", "180deg"] },
  pulse: { scale: [1, 1.08, 1] },
  rollIn: { x: ["-100%", "0%"], rotate: ["-120deg", "0deg"], opacity: [0, 1] },
  rollOut: { x: ["0%", "100%"], rotate: ["0deg", "120deg"], opacity: [1, 0] },
  scaleUp: { scale: [1, 1.2] },
  scaleDown: { scale: [1.2, 1] },
  skew: { skewX: ["10deg", "0deg"] },
  colorChange: { backgroundColor: ["#ff6b6b", "#1dd1a1", "#54a0ff"] },
  morph: {}, // placeholder; handled by SVG path 'd' animation separately
  float: { y: ["0px", "-20px", "0px"] },
  glow: { boxShadow: ["0 0 0px rgba(255,255,255,0)", "0 0 12px rgba(255,255,255,0.9)", "0 0 0px rgba(255,255,255,0)"] },
  wave: { y: ["0px", "-10px", "0px"], rotate: ["0deg", "2deg", "0deg"] },
  swing: { rotate: ["0deg", "15deg", "0deg"], transformOrigin: "top center" },
  wobble: { x: ["0%", "-5%", "0%"], rotate: ["0deg", "-5deg", "0deg"] },
  blurIn: { opacity: [0, 1], filter: ["blur(12px)", "blur(0px)"] },
  blurOut: { opacity: [1, 0], filter: ["blur(0px)", "blur(12px)"] },
  staggerSlideUp: { y: ["30px", "0px"], opacity: [0, 1] },
  typewriter: { opacity: [0, 1] },
  gradientShift: { background: ["linear-gradient(45deg,#ff6b6b,#1dd1a1)", "linear-gradient(45deg,#1dd1a1,#54a0ff)"] },
  neonPulse: { textShadow: ["0 0 3px #fff", "0 0 8px #ff00de", "0 0 3px #fff"] },
  magneticPull: { x: ["0px", "10px", "0px"], y: ["0px", "-10px", "0px"] },
  liquidFill: { clipPath: ["polygon(0 100%,100% 100%,100% 100%,0 100%)", "polygon(0 0%,100% 0%,100% 100%,0 100%)"], opacity: [0, 1] },
  parallaxTilt: { rotateX: ["0deg", "10deg"], rotateY: ["0deg", "5deg"] },
};

export const effectTransitions: Partial<Record<string, { duration?: number; easing?: string; iterations?: number | typeof Infinity }>> = {
  fadeIn: { duration: 0.6, easing: "ease-out" },
  fadeOut: { duration: 0.5, easing: "ease-in" },
  slideInLeft: { duration: 0.8, easing: "ease-out" },
  slideInRight: { duration: 0.8, easing: "ease-out" },
  slideInUp: { duration: 0.8, easing: "ease-out" },
  slideInDown: { duration: 0.8, easing: "ease-out" },
  zoomIn: { duration: 0.7, easing: "ease-out" },
  zoomOut: { duration: 0.7, easing: "ease-in" },
  bounce: { duration: 0.9, easing: "cubic-bezier(.2,.9,.2,1)" },
  pulse: { duration: 1.0, easing: "ease-in-out", iterations: 1 },
  float: { duration: 3, easing: "ease-in-out", iterations: Infinity },
  glow: { duration: 2, easing: "ease-in-out", iterations: Infinity },
  wave: { duration: 1.5, easing: "ease-in-out" },
  swing: { duration: 1.2, easing: "ease-in-out" },
  wobble: { duration: 0.9, easing: "ease-in-out" },
  blurIn: { duration: 0.9, easing: "ease-out" },
  blurOut: { duration: 0.9, easing: "ease-in" },
  neonPulse: { duration: 1.2, easing: "ease-in-out", iterations: Infinity },
  gradientShift: { duration: 4, easing: "linear", iterations: Infinity },
  magneticPull: { duration: 1.2, easing: "ease-in-out" },
  liquidFill: { duration: 1.1, easing: "ease-out" },
  parallaxTilt: { duration: 1.5, easing: "ease-in-out" },
  staggerSlideUp: { duration: 0.55, easing: "ease-out" },
  typewriter: { duration: 2, easing: "steps(1)" },
  
};
